spring.application.name=market_platform

#PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/market_platform
spring.datasource.username=postgres
spring.datasource.password=agbo1212#
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=6000

#Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=classpath:env.properties


#logging.level.org.springframework=DEBUG

# Email notification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-specific-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth 2.0 with Google
#spring.security.oauth2.client.registration.google.client-id=your-google-client-id
#spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
#spring.security.oauth2.client.registration.google.scope=openid,email,profile
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=sub

#Cloudinary configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key= ${CLOUDINARY_API_KEY}
cloudinary.api-secret= ${CLOUDINARY_API_SECRET}


# Kafka Setup
# ===============================
#spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# Producer Configuration
# ===============================
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.ack=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# ===============================
# Consumer Configuration
# ===============================
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=market-platform-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

# Trusted packages for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.doziem.market_platform.*

# ===============================
# Listener Configuration
# ===============================
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=3
spring.kafka.listener.type=batch

# ===============================
# Topic Configuration (Optional)
# ===============================
kafka.topic.product-notification=product-notification


alert.email.from= ${ALERT_EMAIL_FROM}
alert.email.admin= ${ALERT_EMAIL_ADMIN}
